# Site settings
title: 九皋
email: c.svenjax@gmail.com
description: "鹤鸣于九皋，声闻于天。"
baseurl: ""
url: "http://localhost:4000"

# Owner/author information
owner:
  name:           Svenja
  avatar:         avatar.jpg
  bio:            "Always alive."
  email:          c.svenjax@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        csvenja
  facebook:
  github:         csvenja
  stackexchange:
  linkedin:
  instagram:
  flickr:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
