# Site settings
title: 九皋
email: c.svenjax@gmail.com
description: ""
baseurl: ""
url: "http://svenja.im"
twitter_username: csvenja
github_username:  csvenja

# Build settings
markdown: kramdown
permalink: pretty
